safe: false
lsi: false
highlighter: true
permalink: /post/:title

name: The Pretengineer
description: The Pretengineer is kind of a blog, mostly written by Jack Pearkes, but other folks contribute. Each post has a list of contributors at the bottom.
url: http://pretengineer.com
